# Generated by Django 5.2.3 on 2025-08-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
