# Generated by Django 5.2.3 on 2025-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='media/image')),
                ('organizer_name', models.CharField(default='Alpha Run Club', max_length=255)),
                ('contact_email', models.EmailField(default='alpharunclub@gmail.com', max_length=254, null=True)),
                ('contact_phone', models.CharField(default='9403253509', max_length=15, null=True)),
                ('event_type', models.CharField(choices=[('networking_run', 'Networking Run'), ('coffee_rave_run', 'Coffee Rave Run'), ('bootcamp', 'BootCamp'), ('community_event', 'Community Event'), ('others', 'Others')], default='networking_run', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('registration_required', models.BooleanField(default=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cta_text', models.CharField(default='Register Now', max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past'), ('cancelled', 'Cancelled'), ('draft', 'Draft')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
