# Generated by Django 5.2.3 on 2025-09-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_event_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallery',
        ),
    ]
