# Generated by Django 5.2.3 on 2025-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_remove_event_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.URLField(blank=True, help_text='Link to Google Photos', null=True),
        ),
    ]
